spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisq
    username: root
    password: iamchenjie
    
logging:
  level:
    root: DEBUG
    
mybatis:
  mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml
  
server:
  port: 8081
